version: '3'
services:
  mysql:
    image: mysql:5.7
    # networks:
    #   - host
    ports:
      - 3306:3306
    #   - 5555:5555
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    #   - mysql-data:/var/lib/mysql
    #   - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      # MYSQL_ROOT_PASSWORD: root 
      # MYSQL_USER: mysql
      # MYSQL_PASSWORD: mysql 
      MYSQL_DATABASE: test

# volumes:
#   mysql-data:
#     external:
#       name: mysql57_volume
