version: '3'
services:
  mongo:
    image: mongo
    # networks:
    #   - host
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "test"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
